# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [166]:
import os
import numpy as np
import pandas as pd

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [3]:
ls = [i for i in range(1,51)]
print(ls)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [5]:
ls_2 = [i for i in range (2,201) if i%2==0]
print(ls_2)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]


### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [6]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

In [118]:

l_c = a.tolist()
l3 = [f for e in l_c for f in e]
print(l3)

[0.84062117, 0.48006452, 0.7876326, 0.77109654, 0.44409793, 0.09014516, 0.81835917, 0.87645456, 0.7066597, 0.09610873, 0.41247947, 0.57433389, 0.29960807, 0.42315023, 0.34452557, 0.4751035, 0.17003563, 0.46843998, 0.92796258, 0.69814654, 0.41290051, 0.19561071, 0.16284783, 0.97016248, 0.71725408, 0.87702738, 0.31244595, 0.76615487, 0.20754036, 0.57871812, 0.07214068, 0.40356048, 0.12149553, 0.53222417, 0.9976855, 0.12536346, 0.80930099, 0.50962849, 0.94555126, 0.33364763]


### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [123]:
l4 = [f for e in l_c for f in e if f >= .5]
print(l4)

[0.84062117, 0.7876326, 0.77109654, 0.81835917, 0.87645456, 0.7066597, 0.57433389, 0.92796258, 0.69814654, 0.97016248, 0.71725408, 0.87702738, 0.76615487, 0.57871812, 0.53222417, 0.9976855, 0.80930099, 0.50962849, 0.94555126]


### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [125]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])

In [162]:
l_l = b.tolist()
#print(l_l)
l6 = [x for i in l_l for j in i for x in j ]
#print(l6)
#for i in l_l:
#    for j in i:
#        for x in j:
 #           l6.append(x)
print(l6)

[0.55867166, 0.06210792, 0.08147297, 0.82579068, 0.91512478, 0.06833034, 0.05440634, 0.65857693, 0.30296619, 0.06769833, 0.96031863, 0.51293743, 0.09143215, 0.71893382, 0.45850679, 0.58256464, 0.59005654, 0.56266457, 0.71600294, 0.87392666, 0.11434044, 0.8694668, 0.65669313, 0.10708681, 0.07529684, 0.46470767, 0.47984544, 0.65368638, 0.14901286, 0.23760688]


### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [165]:
l_u = [x for i in l_l for i in i for x in j if x >= .5]
print(l_u)

[0.65368638, 0.65368638, 0.65368638, 0.65368638, 0.65368638, 0.65368638, 0.65368638, 0.65368638, 0.65368638, 0.65368638]


### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [180]:
path = 'C:/Users/Data Analyst/Documents/GitHub\datamex0120/module-1/lab-list-comprehensions/data'
table_list = [(filename) for filename in os.listdir(path) if filename.endswith('.csv')]

print(table_list)

['sample_file_0.csv', 'sample_file_1.csv', 'sample_file_2.csv', 'sample_file_3.csv', 'sample_file_4.csv', 'sample_file_5.csv', 'sample_file_6.csv', 'sample_file_7.csv', 'sample_file_8.csv', 'sample_file_9.csv']


### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [188]:
import glob
os.chdir("C:/Users/Data Analyst/Documents/GitHub\datamex0120/module-1/lab-list-comprehensions/data")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
df = combined_csv.head(n=10)
print(df)

          0         1         2         3         4         5         6  \
0  0.734751  0.195362  0.734309  0.598184  0.763433  0.263434  0.868066   
1  0.772607  0.445391  0.249642  0.787922  0.598583  0.827238  0.624126   
2  0.226428  0.268764  0.694262  0.622335  0.063843  0.122683  0.815625   
3  0.362748  0.495430  0.113876  0.594149  0.612522  0.625204  0.864050   
4  0.033415  0.340433  0.464971  0.363737  0.025815  0.434129  0.415163   
0  0.276827  0.260054  0.942397  0.113187  0.781355  0.475740  0.152061   
1  0.995885  0.158381  0.244274  0.962163  0.651900  0.930665  0.577190   
2  0.641917  0.821055  0.392437  0.782617  0.510762  0.428320  0.017324   
3  0.806532  0.569258  0.148175  0.809987  0.459632  0.735762  0.730664   
4  0.311185  0.501165  0.365979  0.782807  0.776795  0.797199  0.791946   

          7         8         9        10        11        12        13  \
0  0.058092  0.753502  0.587513  0.311608  0.178356  0.182922  0.147631   
1  0.601524  0.688753  0

### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [245]:
c = list(df.columns)

In [274]:
y = [df[i] for i in c]
e = []
for i in range(1,21):
    z = mean(y[i])
    if z >.45:
            e.append(z)
            print(y[i],c[i])

0    0.598184
1    0.787922
2    0.622335
3    0.594149
4    0.363737
0    0.113187
1    0.962163
2    0.782617
3    0.809987
4    0.782807
Name: 3, dtype: float64 3
0    0.763433
1    0.598583
2    0.063843
3    0.612522
4    0.025815
0    0.781355
1    0.651900
2    0.510762
3    0.459632
4    0.776795
Name: 4, dtype: float64 4
0    0.263434
1    0.827238
2    0.122683
3    0.625204
4    0.434129
0    0.475740
1    0.930665
2    0.428320
3    0.735762
4    0.797199
Name: 5, dtype: float64 5
0    0.868066
1    0.624126
2    0.815625
3    0.864050
4    0.415163
0    0.152061
1    0.577190
2    0.017324
3    0.730664
4    0.791946
Name: 6, dtype: float64 6
0    0.058092
1    0.601524
2    0.584542
3    0.260279
4    0.892210
0    0.250324
1    0.087914
2    0.680720
3    0.934502
4    0.847157
Name: 7, dtype: float64 7
0    0.753502
1    0.688753
2    0.032594
3    0.528873
4    0.381701
0    0.147078
1    0.960261
2    0.340412
3    0.080322
4    0.771811
Name: 8, dtype: float64 8
0   

### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [236]:
df['20'] = [i-0.1 for i in df['19']]
df.head()

C:\Users\Data Analyst\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


0         1         2         3         4         5         6  \
0  0.734751  0.195362  0.734309  0.598184  0.763433  0.263434  0.868066   
1  0.772607  0.445391  0.249642  0.787922  0.598583  0.827238  0.624126   
2  0.226428  0.268764  0.694262  0.622335  0.063843  0.122683  0.815625   
3  0.362748  0.495430  0.113876  0.594149  0.612522  0.625204  0.864050   
4  0.033415  0.340433  0.464971  0.363737  0.025815  0.434129  0.415163   

          7         8         9  ...        11        12        13        14  \
0  0.058092  0.753502  0.587513  ...  0.178356  0.182922  0.147631  0.391188   
1  0.601524  0.688753  0.338870  ...  0.471474  0.267443  0.453351  0.800716   
2  0.584542  0.032594  0.589775  ...  0.650973  0.565705  0.691784  0.265223   
3  0.260279  0.528873  0.168043  ...  0.677014  0.175735  0.632370  0.926715   
4  0.892210  0.381701  0.415264  ...  0.696930  0.819751  0.944029  0.869965   

         15        16        17        18        19        20  
0  0.816049  0.749068  0.293260  0.937828  0.880858  0.780858  
1  0.045749  0.683793  0.389789  0.016787  0.503695  0.403695  
2  0.739031  0.560394  0.334802  0.517694  0.646110  0.546110  
3  0.085675  0.120525  0.141746  0.771144  0.489660  0.389660  
4  0.041723  0.819140  0.676051  0.109349  0.872947  0.772947  

[5 rows x 21 columns]

### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.

In [244]:
d = [x for x in df.values for i in x if i >.5 and i <=.75]
d

[array([0.73475109, 0.19536155, 0.73430923, 0.59818415, 0.76343342,
        0.26343379, 0.86806635, 0.0580925 , 0.75350236, 0.587513  ,
        0.31160828, 0.17835554, 0.18292213, 0.14763099, 0.39118786,
        0.81604939, 0.74906808, 0.29326038, 0.93782846, 0.8808575 ,
        0.7808575 ]),
 array([0.73475109, 0.19536155, 0.73430923, 0.59818415, 0.76343342,
        0.26343379, 0.86806635, 0.0580925 , 0.75350236, 0.587513  ,
        0.31160828, 0.17835554, 0.18292213, 0.14763099, 0.39118786,
        0.81604939, 0.74906808, 0.29326038, 0.93782846, 0.8808575 ,
        0.7808575 ]),
 array([0.73475109, 0.19536155, 0.73430923, 0.59818415, 0.76343342,
        0.26343379, 0.86806635, 0.0580925 , 0.75350236, 0.587513  ,
        0.31160828, 0.17835554, 0.18292213, 0.14763099, 0.39118786,
        0.81604939, 0.74906808, 0.29326038, 0.93782846, 0.8808575 ,
        0.7808575 ]),
 array([0.73475109, 0.19536155, 0.73430923, 0.59818415, 0.76343342,
        0.26343379, 0.86806635, 0.0580925 , 0.7535